"""End-to-end experiment orchestration and artifact generation."""

from __future__ import annotations

import hashlib
import json
import platform
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd
import sklearn

from .config import DEFAULT_DATA_PATH, FIGURE_DIR, REPORT_DIR, ExperimentConfig
from .modeling import (
    partition_labels,
    run_anomaly_detection,
    run_clustering,
    run_forecasting,
    temporal_boundaries,
)
from .synthetic import generate_data, save_data, validate_data
from .visualization import (
    plot_anomaly_diagnostics,
    plot_cluster_diagnostics,
    plot_forecast_diagnostics,
    plot_load_profiles,
)


def _fingerprint(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _native(value):
    """Convert NumPy/pandas values into JSON-native values."""

    if isinstance(value, dict):
        return {str(key): _native(item) for key, item in value.items()}
    if isinstance(value, (list, tuple)):
        return [_native(item) for item in value]
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.floating,)):
        return None if np.isnan(value) else float(value)
    if isinstance(value, float) and np.isnan(value):
        return None
    if isinstance(value, (pd.Timestamp,)):
        return value.isoformat()
    return value


def _write_results_summary(results: dict, output_path: Path) -> None:
    forecast = {row["model"]: row for row in results["forecasting"]["models"]}
    forest = forecast["random_forest"]
    persistence = forecast["persistence"]
    skill = 100 * (1 - forest["mae_kwh"] / persistence["mae_kwh"])
    anomaly = results["anomaly_detection"]
    cluster = results["clustering"]
    interval = results["forecasting"]["prediction_interval"]
    calibration_start = results["split"]["calibration_start"]
    test_start = results["split"]["test_start"]
    mae_interval = (
        f"{forest['mae_ci95_lower_kwh']:.4f}–"
        f"{forest['mae_ci95_upper_kwh']:.4f}"
    )

    text = f"""# Reproducible experiment results

This file is generated by `python src/train_models.py`. It reports results from a
strict chronological split shared across tasks; it is not a manually selected run.

## Experimental protocol

- Training: timestamps before `{results['split']['calibration_start']}`
- Calibration: `{calibration_start}` to before `{test_start}`
- Test: `{results['split']['test_start']}` through `{results['split']['end']}`
- Random seed: `{results['experiment']['seed']}`
- Dataset SHA-256: `{results['dataset']['sha256']}`

## Findings

1. **Forecasting.** Random forest achieved MAE **{forest['mae_kwh']:.4f} kWh**
   (95% day-block bootstrap interval {mae_interval})
   and RMSE **{forest['rmse_kwh']:.4f} kWh** on the held-out period. Its MAE was
   **{skill:.1f}% lower** than persistence. The nominal 95% split-conformal interval
   obtained **{100 * interval['empirical_coverage']:.1f}% empirical coverage**.
2. **Anomaly detection.** The label-free Isolation Forest achieved held-out F1
   **{anomaly['f1']:.3f}**, average precision **{anomaly['average_precision']:.3f}**,
   and recall **{anomaly['recall']:.3f}** against injected events.
3. **Segmentation.** Silhouette selection chose **K={cluster['selected_k']}** with
   silhouette **{cluster['silhouette_score']:.3f}**. Agreement with the hidden
   simulation regimes was ARI **{cluster['adjusted_rand_index_vs_latent_type']:.3f}**.
   As a sensitivity check, setting K to the known {cluster['latent_regime_count']}
   regimes yielded ARI **{cluster['ari_at_latent_regime_count']:.3f}**. This contrast
   is evidence that an internal clustering criterion can prefer a coarser behavioral
   taxonomy even when finer data-generating regimes are recoverable.

## Interpretation boundary

These are controlled synthetic-data results, useful for validating methodology and
software behavior. They are not evidence of deployment performance, theft, fraud,
or customer intent. External validation on real meters, weather feeds, and local
tariff conditions is required before operational use.
"""
    output_path.write_text(text, encoding="utf-8")


def run_experiment(
    data_path: str | Path = DEFAULT_DATA_PATH,
    config: ExperimentConfig | None = None,
    regenerate: bool = False,
) -> dict:
    """Run the complete experiment and persist figures plus machine-readable results."""

    config = config or ExperimentConfig()
    config.validate()
    path = Path(data_path)
    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    if regenerate or not path.exists():
        save_data(generate_data(seed=config.seed), path)
    data = pd.read_csv(path, parse_dates=["timestamp"])
    quality = validate_data(data)
    boundaries = temporal_boundaries(data, config)
    partitions = partition_labels(data["timestamp"], boundaries)

    # Segmentation is fit to the training period so future consumption cannot shape it.
    cluster_result = run_clustering(data.loc[partitions.eq("train")], seed=config.seed)
    anomaly_result = run_anomaly_detection(data, boundaries, config)
    forecast_result = run_forecasting(data, boundaries, config)

    plot_load_profiles(data.loc[partitions.eq("train")], FIGURE_DIR / "load_profiles.png")
    plot_cluster_diagnostics(cluster_result, FIGURE_DIR / "customer_clusters.png")
    plot_anomaly_diagnostics(
        anomaly_result,
        FIGURE_DIR / "anomaly_confusion_matrix.png",
        FIGURE_DIR / "anomaly_precision_recall.png",
    )
    plot_forecast_diagnostics(
        forecast_result,
        FIGURE_DIR / "forecast_model_comparison.png",
        FIGURE_DIR / "forecast_actual_vs_predicted.png",
    )

    cluster_profiles = cluster_result["profiles"].copy()
    cluster_profiles.to_csv(REPORT_DIR / "cluster_profiles.csv", index=False)
    cluster_result["selection"].to_csv(REPORT_DIR / "cluster_selection.csv", index=False)
    forecast_result["metrics"].to_csv(REPORT_DIR / "forecast_metrics.csv", index=False)
    forecast_result["feature_importance"].to_csv(
        REPORT_DIR / "forecast_feature_importance.csv", index=False
    )

    split_counts = (
        pd.DataFrame({"timestamp": data["timestamp"], "partition": partitions})
        .groupby("partition", observed=True)["timestamp"]
        .nunique()
        .to_dict()
    )
    results = {
        "experiment": {
            "seed": config.seed,
            "train_fraction": config.train_fraction,
            "calibration_fraction": config.calibration_fraction,
            "test_fraction": 1 - config.train_fraction - config.calibration_fraction,
            "interval_alpha": config.interval_alpha,
            "anomaly_contamination": config.anomaly_contamination,
        },
        "dataset": {**quality, "path": path.as_posix(), "sha256": _fingerprint(path)},
        "split": {
            "calibration_start": boundaries.calibration_start,
            "test_start": boundaries.test_start,
            "end": boundaries.end,
            "unique_timestamps_by_partition": split_counts,
        },
        "clustering": cluster_result["metrics"],
        "anomaly_detection": anomaly_result["metrics"],
        "forecasting": {
            "models": forecast_result["metrics"].to_dict(orient="records"),
            "prediction_interval": forecast_result["interval_metrics"],
        },
        "environment": {
            "python": platform.python_version(),
            "pandas": pd.__version__,
            "numpy": np.__version__,
            "scikit_learn": sklearn.__version__,
            "matplotlib": matplotlib.__version__,
        },
    }
    results = _native(results)
    (REPORT_DIR / "metrics.json").write_text(
        json.dumps(results, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    (REPORT_DIR / "data_quality.json").write_text(
        json.dumps(_native(quality), indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    _write_results_summary(results, REPORT_DIR / "results.md")
    return results
